#!/usr/bin/env python3
"""Writes crates/supervisor/src/model_shape.rs: the tensor names and byte lengths the graph implements.

Usage: python3 scripts/gen_model_shape.py MANIFEST BUILD

MANIFEST is the `manifest.json` that `neural-forge-cli extract-model` wrote from a build whose
network the vendored graph in third_party/opendlss-nr implements; BUILD is that DLL's build, for
the file comment. Only each tensor's `name` and `byteLength` are read: no tensor bytes, no hashes.
"""

import json
import pathlib
import re
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "crates/supervisor/src/model_shape.rs"


def vendored_commit() -> str:
    upstream = OUT.parents[3] / "third_party/opendlss-nr/UPSTREAM.md"
    found = re.search(r"Commit: `([0-9a-f]{40})`", upstream.read_text())
    if not found:
        sys.exit(f"no commit line in {upstream}")
    return found.group(1)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip().splitlines()[2])
    manifest = json.loads(pathlib.Path(sys.argv[1]).read_text())
    build = sys.argv[2]
    rows = [(t["name"], int(t["byteLength"])) for t in manifest["tensors"]]
    lines = [
        "//! The tensors the graph implements: each name in `WEIGHTS_HT` and its byte length.",
        "//!",
        f"//! Generated by `scripts/gen_model_shape.py` from the manifest `extract-model` wrote from build {build}.",
        "//! The rows describe the network in `third_party/opendlss-nr` at the vendored commit",
        f"//! `{vendored_commit()}`. Bumping the vendored copy to a new network changes this table with it:",
        "//! regenerate it from a manifest of a DLL that carries the new network.",
        "//!",
        "//! Names and lengths only: no tensor bytes and no hashes of them.",
        "",
        "/// `(name, byte length)`, in the manifest's order (stage, then block, layer and parameter).",
        "pub const EXPECTED: &[(&str, u64)] = &[",
    ]
    lines += [f'    ("{name}", {length}),' for name, length in rows]
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT}: {len(rows)} tensors, {sum(length for _, length in rows)} bytes")


if __name__ == "__main__":
    main()
