#!/usr/bin/env python3
"""Generates THIRD_PARTY_CRATES.md: every crate linked into a shipped binary, with its license.

Covers the native default members (layer, GUI, CLI) and the Windows-only helper, walking
normal (non-dev, non-build) dependencies only, since those are what get statically linked.

  gen_third_party_crates.py           rewrite THIRD_PARTY_CRATES.md
  gen_third_party_crates.py --check   exit 1 if it is out of date (for CI)
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_CRATES.md"


def metadata(*extra):
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked", *extra],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    return json.loads(out)


def linked(meta, workspace_names):
    pkgs = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    seen, stack = set(), [i for i, p in pkgs.items() if p["name"] in workspace_names]
    while stack:
        i = stack.pop()
        if i in seen:
            continue
        seen.add(i)
        for dep in nodes[i]["deps"]:
            if any(k["kind"] is None for k in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    return [pkgs[i] for i in seen]


def main():
    rows = {}
    for target in ("x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"):
        meta = metadata("--filter-platform", target)
        members = {p["name"] for p in meta["packages"] if p["source"] is None}
        for p in linked(meta, members):
            if p["source"] is None:
                continue  # this workspace's own crates: AGPL-3.0-or-later, see LICENSE
            rows[(p["name"], p["version"])] = (
                p.get("license") or "see crate", p.get("repository") or p.get("homepage") or "")
    lines = [
        "# Third-party Rust crates",
        "",
        "Statically linked into the Neural Forge binaries (layer, GUI, CLI and the Windows",
        "helper). Generated by `scripts/gen_third_party_crates.py` from `Cargo.lock`; do not edit.",
        "Each crate's own license text is in its published source (crates.io / the repository).",
        "",
        "| Crate | Version | License | Source |",
        "|---|---|---|---|",
    ]
    for (name, version), (lic, repo) in sorted(rows.items()):
        lines.append(f"| {name} | {version} | {lic} | {repo} |")
    text = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text)
    print(f"wrote {OUT.name}: {len(rows)} crates")


main()
